### ISSUE TITLE
run.py got stuck during Gaussian Refinement

### ISSUE THREAD

**Issue by ZhouTimeMachine** [ChenHoy/DROID-Splat#10]
Hello, I download TUM-RGBD data [rgbd_dataset_freiburg1_xyz](https://cvg.cit.tum.de/rgbd/dataset/freiburg1/rgbd_dataset_freiburg1_xyz.tgz) and put it to `data/rgbd_dataset_freiburg1_xyz`. Then I run the command

```
python run.py data.input_folder=data/rgbd_dataset_freiburg1_xyz tracking=base stride=1 mode=rgbd
```

without any change of other configurations. The program stuck at

```
Gaussian Mapper]  Refinement loss: 0.029803577810525894                                                                                   | 0/1 [00:00<?, ?it/s]
Batch Optimization: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.33it/s]
Batch Optimization:   0%|                                                                                                                 | 0/1 [00:00<?, ?it/s]
Gaussian Refinement:  51%|██████████████████████████████████████████████████▌                                                 | 253/500 [00:40<00:39,  6.29it/s]
```

with 2 spawn processes on GPU, one occupies 21.29GiB of GPU-MEM and the other 384.0 MiB. 

I hope other examples or necessary config/code modifications could be provided, so that I can run a demo from start to end. Thanks for suggestions.

**Comment by ChenHoy** [comment]
Hi there, that is odd. Normally it should not get stuck. Without knowing your CUDA, pytorch, etc. versions, I would suggest the following first: 

`python run.py data.input_folder=data/rgbd_dataset_freiburg1_xyz tracking=tum mapping=tum stride=1 backend_every=8 mapper_every=20 mode=rgbd` 

as these are the configs we used on TUM-RGBD. You could also change the ```sleep_delay=0.35``` which is a small cool-off between Processes. If you are close to the RAM limit on your GPU, you could also reduce the resolution or number of Gaussians by changing some of the mapping parameters.

I am not sure why this got stuck, especially without an error message. I hope this helps, I would be happy to resolve this. 
If you could provide an error message, that would be very helpful in case this happens for other users as well :/

**Comment by ZhouTimeMachine** [comment]
Thanks for your reply! I'm sorry that I didn't provide detailed information, but my problem remains reproducible on my ubuntu20.04 machine. I use coda-12.3, and I follow readme to build the environment::

```
git clone --recursive https://github.com/ChenHoy/DROID-Splat.git
cd DROID-Splat
sudo apt-get install libopenexr-dev
conda env create -f environment.yaml
conda activate droidsplat
python setup.py install
```

It seems that there is no error message, only the progress bar appears to get stuck. I use remote-ssh to control the server, and GUI is not enabled. 

I will follow your suggestions to debug after hours of sleep, thanks again for your suggestions. :)

**Comment by ChenHoy** [comment]
No worries, looking forward to what you say tomorrow :) Your setup is very similar to ours in that case. I think I never observed a single Process to get stuck, but it seems to only be the Gaussian Splatting code in this case.

**Comment by ZhouTimeMachine** [comment]
Now I use

```
python run.py data.input_folder=data/rgbd_dataset_freiburg1_xyz tracking=tum mapping=tum stride=1 backend_every=8 mapper_every=20 mode=rgbd
```

to run, and now it works without abnormal high GPU memory. However it still get stuck at https://github.com/ChenHoy/DROID-Splat/blob/main/src/slam.py#L1098-L1099, with

```
ipdb> self.all_finished
tensor([5], dtype=torch.int32)
ipdb> self.num_running_thread
tensor([7], dtype=torch.int32)
ipdb> self.all_finished < self.num_running_thread
tensor([True])
```

The 5 running processes are
```
python run.py data.input_folder=data/rgbd_dataset_freiburg1_xyz tracking=tum mapping=tum stride=1 backend_every=8 mapper_every=20 mode=rgbd
miniconda3/envs/droidsplat/bin/python-cfrom multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=54, pipe_handle=87)--multiprocessing-fork
miniconda3/envs/droidsplat/bin/python-cfrom multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=54, pipe_handle=89)--multiprocessing-fork
```

which occupy GPU memory 2100MiB, 2136MiB and 384.0MiB in order, but GPU utility remains 0. I guess it becomes zombie process? Thanks for any further suggestion.

**Comment by ChenHoy** [comment]
Trying to replicate this, can you give me more info on changed configs? You are on the main branch and use the mapping/tum.yaml as config for mapping, why do you have any refinement? I am seeing right now, that I pushed the configs without any refinement. Will run this on my setup with latest code now.

Comment: Since tum has different intrinsics per sequence, you should also change the config as is done in `scripts/evaluation/evaluate_on_tum.sh`, i.e. for your scene _fr1_xyz_ additionally set `data=TUM_RGBD/fr1` so this uses the right ones.

**Comment by ChenHoy** [comment]
I am very sorry for this. This is odd, I cant reproduce this using no GUI so I am not sure why its gets stuck on your setup :/ 

**Just for clarity**, the current main branch works **with or without GUI** on my setup and does not get stuck independent of refinement as well. 

Does the command: 
`python run.py data=TUM_RGBD/fr1 stride=1 data.input_folder=/your/path/to/scene tracking=tum mapping=tum backend_every=8 mapper_every=20`
not work in your environment? This should be possible, as we can simply override with the file `configs/data/TUM_RGBD/fr1.yaml`. 

Now if you did not change any configs, then the config in `configs/slam.py` will run the mapping_gui automatically, i.e. the flag `run_mapping_gui=True` is set per default. The current push also has the flag `run_loop_detection=False` set automatically. 

Glad if I could help and thank you for that feedback. I would be happy if someone else could confirm this when they encounter this problem, so this potential bug can get fixed.

Cheers
Christian

**Comment by ZhouTimeMachine** [comment]
It works! The default configs are for GUI, so when running without GUI, mannually set `run_mapping_gui: False` in `configs/slam.yaml` is necessary, otherwise it will fall into deadlock.

So I recommend that, if a new user want to run a quick test without GUI, you can download TUM-RGBD data [rgbd_dataset_freiburg1_xyz](https://cvg.cit.tum.de/rgbd/dataset/freiburg1/rgbd_dataset_freiburg1_xyz.tgz), unzip it and put it to some path like `Datasets/rgbd_dataset_freiburg1_xyz`. Then you need to 

- build environment
- set `run_mapping_gui` to False in `configs/slam.yaml`
- run the following command in the environment

```
python run.py data=TUM_RGBD/fr1 data.input_folder=Datasets/rgbd_dataset_freiburg1_xyz tracking=tum mapping=tum stride=1 backend_every=8 mapper_every=20 mode=rgbd
```

That's all for a quick test, then you can debug the code step by step and get familiar with the meanings of configs!

**Comment by ChenHoy** [comment]
Thank you for writing this, I will add this to the documentation later when I find the time. The reasoning behind our decision to set that flag to True, was that likely new users dont want to evaluate the framework on a dataset, but visually see everything on their own image folders. 

Glad, that this was resolved and closed! :)
