### ISSUE TITLE
Did you release the paper?

### ISSUE THREAD

**Issue by YJ-142150** [ChenHoy/DROID-Splat#3]
Thank you for your great work.
Did you release this paper in the arxiv?
I'm willing to read it!

**Comment by ChenHoy** [comment]
Hi, the paper should be released this week! Thank you for your interest :) I will keep you updated

**Comment by ChenHoy** [comment]
I am very sorry for the long delay, but due to deadlines and organizational issues we had to postpone it a little bit. 
You can read the paper at https://arxiv.org/pdf/2411.17660
